### PR TITLE
User stories

### PR DESCRIPTION
**Pull request by sooffia**
Added user stories and created user personas.

### CODE REVIEW

**Review by kimnle — COMMENTED** [review]
For "The app should allow users to filter other travelers by destination, travel dates, and interests." I hadn't thought about filtering by interests to be a feature, do we want to implement this for this user story to make sense or as a stretch goal if we have time? I did write in our functionality/features that "Users create a profile where they share personal travel interests and bio information." Do you think that'd be enough for this user story?

For "Direct messages or connection requests from users should be possible via the platform." Just doing direct messages for this app, no connection requests makes it simpler

**Comment by sooffia** [comment]
My bad for adding the interests filter! After reviewing it, I don't think it’s necessary for this user story, so I’ve removed it. Instead, I’ve created a revision section to explain how we decided to skip connection requests and just stick with direct messages to keep things simple. Also, I’d love to get your thoughts on the toggle feature under itinerary management, plus the privacy controls where users can customise who sees their plans. I also added a point about showing overlapping itineraries when browsing filtered traveler profiles. Do you think these changes work, or should I rethink them?

**Comment by kimnle** [comment]
I think the toggle feature's a great idea, I'll add it in the description features

I think the privacy controls is a stretch idea, maybe remove it for now and if we have time we can add it back in?

**Comment by sooffia** [comment]
Sure, I’ve removed the privacy controls. 😊

**Comment by theresaxn** [comment]
I think the user stories look good but I think there should be a privacy /security aspect in there as well. Like users can toggle their profile setting to public or private. There was also this mentioned as an acceptance criteria:
"The app should allow users to toggle between a detailed list and a simplified view of their itinerary."
But should we specify that a detailed list should only be visible to the user but a simplified view (assuming it's just be travel dates and destination) can be shared publicly. It would be safer for users to could share more specific details like accommodation or activities to other users via direct messages since we wouldn't have control over who views a user's profile or itinerary if they wanted to be public

**Comment by theresaxn** [comment]
What exactly would be on a detailed list vs a simplified view of the itinerary be?
From a security standpoint, if users can add details like accommodation - wouldn't that be a bit dangerous considering we can't control who views their profile/itinerary?

**Comment by sooffia** [comment]
For the detailed vs. simplified view, I think the detailed list could include specifics like activities and notes, while the simplified view might just highlight destinations and dates. As for the accommodation details, that's a good point—I agree we should be cautious about how much personal info users can share.

**Comment by kimnle** [comment]
I think this comment you left is really good idea Theresa, saw it in my email. "I think the user stories look good but I think there should be a privacy/security aspect in there as well. Like users can toggle their profile setting to public or private. There was also this mentioned as an acceptance criteria:
"The app should allow users to toggle between a detailed list and a simplified view of their itinerary."
But should we specify that a detailed list should only be visible to the user but a simplified view (assuming it's just be travel dates and destination) can be shared publicly. It would be safer for users to could share more specific details like accommodation or activities to other users via direct messages since we wouldn't have control over who views a user's profile or itinerary if they wanted to be public"

So users can toggle between a detailed list (dates, destination and activies) and a simplified view (dates and destinations) of their own itinerary but share and see other user's simplified itinerary?

**Comment by theresaxn** [comment]
I thought my original comment was a bit contradicting to your comment on the privacy controls so I thought I should delete it but awesome if you also agree with it!

**Comment by sooffia** [comment]
Thanks for the feedback! I'll go ahead and add the following:
Users should be able to toggle between a detailed itinerary (dates, destinations, activities) and a simplified itinerary (dates, destinations), and share/view other's simplified itineraries.

I was thinking of adding to the revision section that after discussing privacy concerns with users, we realised the importance of giving them control over the visibility of their itinerary details. Based on their input, we've decided to make the simplified itinerary view (which includes dates and destinations) publicly shareable, while keeping the detailed itinerary (which includes dates, destinations, activities) private to the user. Users have the option to share more detailed information through direct messages. 

What do you guys think about that?

**Comment by theresaxn** [comment]
Hi Sofia, that sounds great! Thank you

**Comment by kimnle** [comment]
Sounds great!!

**Comment by sooffia** [comment]
Hey, I updated my section. Let me know if there's anything you'd like me to change or if you're unsure about anything.

**Comment by kimnle** [comment]
Just need to change the interests part in "Simple Search & Discovery:
The app’s search functionality lets Jessica filter travelers by destination, travel dates, and interests, making it easier to find the perfect subjects for her blog and photography projects."

Everything else looks good!!

**Comment by sooffia** [comment]
So sorry—I completely missed that! I've just removed it.

**Review by theresaxn — APPROVED** [review]

**Review by kimnle — APPROVED** [review]

**Pull request merged**
